### ISSUE TITLE
Compatibility with preCICE v3

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#235]
At some point in the next year, preCICE v3 is coming. We need to update the adapter accordingly.

Changes to consider:

- [x] Drop issue https://github.com/precice/openfoam-adapter/issues/3
- [x] Merged `initializeData` into `intialize`: https://github.com/precice/precice/pull/1350 -> Solved by #266.
- [x] Updated connectivity API (adjust `setMeshEdges` and `setMeshTriangles` to use vertex IDs): https://github.com/precice/precice/pull/1322, https://github.com/precice/precice/issues/1321 -> Solved by #297.
- [x] Updated actions/checkpointing API: https://github.com/precice/precice/issues/719 -> Solved by #285
- [ ] Unsigned sizes: https://github.com/precice/precice/issues/405
- [ ] (additional) Exiting the coupling earlier, if needed: https://github.com/precice/precice/issues/1118
- [x] Apply any waveform iteration related changes needed. -> Solved by #285.

**Comment by MakisH** [comment]
The adapter supports preCICE v3 since v1.3.0.
